### ISSUE TITLE
Plugin maturity

### ISSUE THREAD

**Issue by hatt** [sensu-plugins/sensu-plugins.github.io#6]
Over in Logstash, we use a :milestone symbol in plugins to indicate how mature/maintained a plugin is. The automatic documentation parses the plugin code to show users deciding which plugins to install/use how stable it is. The rough guideline is 0 for unmaintained, 1 for alpha and requesting feedback, 2 for beta and generally backwards compatible, and 3 for stable with backwards compatibility and testing across versions.

Given the state of many plugins at the moment, I think this would be a worthwhile idea in Sensu as well and would tie in nicely with the generated documentation page in #2. Any thoughts from the community?

**Comment by mattyjones** [comment]
I think that is a very good idea.  Especially with the number of plugins it makes good sense as some are very rarely touched.

The auto documentation is still somewhat of a pipedream but gets closer as I have free time to work on stuff.  Feel free to contribute code as well as great ideas.

**Comment by mattyjones** [comment]
@hatt I have implemented this using gem metadata that can be queried by the user and will be floated up to the site as you suggested.

I will be updated the developer docs shortly with details

Thanks!
